### ISSUE TITLE
Existing entries get overwritten

### ISSUE THREAD

**Issue by trianglePB** [tillig/FirefoxNtlmAuth#23]
If you have configured "network.negotiate-auth.trusted-uris" or "network.negotiate-auth.delegation-uris" to some domain and use the FirefoxNtlmAuth
plugin you won't see the already configured domains.
If you then use the plugin to configure a new domain, you will overwrite the existing values.

This is unexpected behaviour leading to a possible loss of configuration values.

Experienced in Firefox 36.0.1.

I would like to configure the values separately if possible.

**Comment by tillig** [comment]
If you want to configure the values separately (e.g., if you already know enough about what they do that you know you need different values) **then this add-in probably isn't for you**. All of the values are currently intentionally kept in sync to keep settings simple.

However, I could update it so that, on initial read, instead of assuming it's in sync to start with, I use the first non-empty key (if one is found). In this case, there is still the potential for data loss (e.g., if you have the two fields individually configured but configured *differently*) but it might solve the issue you were seeing.

Let me know what you think of that proposal.

**Comment by trianglePB** [comment]
In my configuration I only needed "network.negotiate-auth.trusted-uris". So I was surprised that it got overwritten by the plugin. Since I don't need the other values and don't know what security implications they might have, I only used the auth methods I needed.
But if you could change it so that it reads the values of all configuration keys and merge them to a common list would be the best. That way I could at least use the plugin without checking for different settings.

**Comment by tillig** [comment]
I don't think I'd be interested in *merging* them all because that potentially causes other issues, like the inability to remove a setting because you'd have to remove that setting from all of the keys simultaneously.

I think the best I'd be willing to do is pick the first non-empty entry and use that. If that won't work, then maybe I just add an entry to a "known issues" section of the wiki and call it good.

**Comment by trianglePB** [comment]
Is there a need to read the configuration between writing the separate values?
Don't you only read them initially when you open the plugin? How can they change while the plugin is still open?

**Comment by tillig** [comment]
Group policy, script, other plugins... there's no "lock" on config settings.

However, from a merge perspective, I'm worried about:

1. Open about:config.
2. Modify just one of the keys.
3. Use the plugin.
4. How come that setting I just removed is back? (Because of the merge.)

There's no "last modified" either, so I don't really know which was the most recently changed setting.

**Honestly, the intent of the plugin here is to keep things as super simple as possible.** The 90% case need is that all of these settings end up being the same. Most folks using the plugin don't even know the settings exist, so providing an easier way to access them is helpful. The few folks who actually do know they exist, like yourself, may not be the best audience for this plugin; you already know how to use `about:config` to do the modification and I'm not extra interested in making this the End All Be All Configuration Plugin for Passthrough Auth. It does what most people need it to do.

I *am* willing to do a "best guess" when starting up to see if I'm encountering some empty settings keys and some non-empty and pick one of the non-empty keys as the starting point for synchronization. That's probably the best I can offer.

If you're interested in more than that, I'm happy to talk about adding features via pull request, but the simplicity has to remain for the majority case. It would have to be something like "click a button to get an advanced settings view" or "if there are conflicts between different settings ask the user to do the merge and provide a merge screen" or something like that - something that keeps the simplicity but allows for the more complex flows.

**Comment by trianglePB** [comment]
I see your point, because then I wanted to recommend the plugin to some inexperienced user.
But from a screenshot of that user I know that there were other  configuration entries set. Since I don't know how they were set maybe by a script I would not like to see them deleted for whatever reason. I just don't know if they are important.
I just think it would be asked too much of the user to guess that using a plugin "broke" the other web application that "always worked".
At least you should document it prominently that using the plugin could result lost configuration entries.

**Comment by tillig** [comment]
Sounds good. I'll add a note to the wiki so folks are aware.

**Comment by tillig** [comment]
[Updated the wiki with relevant info.](https://github.com/tillig/FirefoxNtlmAuth/wiki)

**Comment by trianglePB** [comment]
I think that the following sentence in the wiki

> If you don't know what any of this means you're probably just fine to use the add-on.

is misleading and that the issue is not only for someone who has "already manually" added values to the mentioned keys.
As you've already said there are many ways to configure Firefox through other ways. 
The user might not even be aware that there is something already configured. To make sure he would have to check the values manually before using the plugin or otherwise he will delete the values that some script or the administrator or whoever set (on installation).
You should make that clear in the wiki that the user has to check if there are "conflicting" configurations before using the plugin.
BTW: I personally do not consider this issue an enhancement, to me unexpected behaviour in combination with data loss is a bug.
