### ISSUE TITLE
Please enable multiprocessing for new FF versions

### ISSUE THREAD

**Issue by boomer57** [tillig/FirefoxNtlmAuth#24]
In FF50+, this add-on is flagged as not multi-processing compatible. This will be a growing problem as the new FireFox multiprocessing capability is enabled in the future.

**Comment by tillig** [comment]
I'm not entirely sure what this will entail. [It seems that in "WebExtensions" there are some changes to how UI should render](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Comparison_with_the_Add-on_SDK) but I'm unclear on how much work that will be. I also don't know if being multi-processing aware is interesting or matters for this extension since it only provides a simple UI on top of changing settings that already exist - it doesn't actually _do any of the auth_ and there aren't any resident scripts or background processes involved.

If folks know how to update easily, let me know or send me a PR. I'm not sure I'll get to this in the immediate future, especially since I'm mostly using Chrome nowadays.

**Comment by tillig** [comment]
Given the add-on is being deprecated by the new plugin model of Firefox where plugins can no longer access browser settings, I'm going to be unable to address this or any other issues. [See the wiki for more details.](https://github.com/tillig/FirefoxNtlmAuth/wiki)
